### ISSUE TITLE
login and .NET 5

### ISSUE THREAD

**Issue by weedkiller** [krzysiex01/HRWebApplication#1]
hi how to login or rather whats the login and can you update to .NET 5 please
it would be nice to use identity for login

**Comment by krzysiex01** [comment]
Application is set up to use Azure Active Directory B2C, so in order to login you have to provide valid AzureAdB2C configuration in _appsettings.json_. Then just register or use existing account in your AD. For convenience you can also use `OnModelCreating(ModelBuilder modelBuilder)` method to seed your database with default admin account.

There are currently no plans to migrate app to .NET 5.

**Comment by weedkiller** [comment]
thanks
